### ISSUE TITLE
NotImplementedError: resource_filename() only supported for .egg, not .zip

### ISSUE THREAD

**Issue by scarygliders** [GameMaker2k/PyUPC-EAN#4]
This error occurs after freezing an application using cx_freeze, which utilises PyUPC-EAN.

The full error message:

> Traceback (most recent call last):
>   File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
>     exec(code, m.__dict__)
>   File "datastar.py", line 23, in <module>
>   File "c:\python\32-bit\3.4\lib\importlib\_bootstrap.py", line 2237, in _find_and_load
>   File "c:\python\32-bit\3.4\lib\importlib\_bootstrap.py", line 2226, in _find_and_load_unlocked
>   File "c:\python\32-bit\3.4\lib\importlib\_bootstrap.py", line 1191, in _load_unlocked
>   File "c:\python\32-bit\3.4\lib\importlib\_bootstrap.py", line 1161, in _load_backward_compatible
>   File "C:\Python34\lib\site-packages\pyupc_ean-2.7.15-py3.4.egg\upcean\__init__.py", line 40, in <module>
>     import upcean.validate, upcean.convert, upcean.support, upcean.getprefix, upcean.oopfuncs;
>   File "c:\python\32-bit\3.4\lib\importlib\_bootstrap.py", line 2237, in _find_and_load
>   File "c:\python\32-bit\3.4\lib\importlib\_bootstrap.py", line 2226, in _find_and_load_unlocked
>   File "c:\python\32-bit\3.4\lib\importlib\_bootstrap.py", line 1191, in _load_unlocked
>   File "c:\python\32-bit\3.4\lib\importlib\_bootstrap.py", line 1161, in _load_backward_compatible
>   File "C:\Python34\lib\site-packages\pyupc_ean-2.7.15-py3.4.egg\upcean\oopfuncs\__init__.py", line 19, in <module>
>     from upcean.oopfuncs.oopfuncs import *;
>   File "c:\python\32-bit\3.4\lib\importlib\_bootstrap.py", line 2237, in _find_and_load
>   File "c:\python\32-bit\3.4\lib\importlib\_bootstrap.py", line 2226, in _find_and_load_unlocked
>   File "c:\python\32-bit\3.4\lib\importlib\_bootstrap.py", line 1191, in _load_unlocked
>   File "c:\python\32-bit\3.4\lib\importlib\_bootstrap.py", line 1161, in _load_backward_compatible
>   File "C:\Python34\lib\site-packages\pyupc_ean-2.7.15-py3.4.egg\upcean\oopfuncs\oopfuncs.py", line 20, in <module>
>     import upcean.fonts, upcean.xml, upcean.barcodes;
>   File "c:\python\32-bit\3.4\lib\importlib\_bootstrap.py", line 2237, in _find_and_load
>   File "c:\python\32-bit\3.4\lib\importlib\_bootstrap.py", line 2226, in _find_and_load_unlocked
>   File "c:\python\32-bit\3.4\lib\importlib\_bootstrap.py", line 1191, in _load_unlocked
>   File "c:\python\32-bit\3.4\lib\importlib\_bootstrap.py", line 1161, in _load_backward_compatible
>   File "C:\Python34\lib\site-packages\pyupc_ean-2.7.15-py3.4.egg\upcean\fonts\__init__.py", line 26, in <module>
>     fontpathocra = pkg_resources.resource_filename(__name__, "OCRA.otf");
>   File "C:\Python34\lib\site-packages\pkg_resources\__init__.py", line 1171, in resource_filename
>     self, resource_name
>   File "C:\Python34\lib\site-packages\pkg_resources\__init__.py", line 1872, in get_resource_filename
>     "resource_filename() only supported for .egg, not .zip"
> NotImplementedError: resource_filename() only supported for .egg, not .zip

**Comment by HCLS-GitRepo** [comment]
what was the resolution for this issue?  I am encountering he same, appreciate resolution info
